# Generated by Django 3.2.4 on 2021-06-22 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rented',
            field=models.BooleanField(default=datetime.datetime.now),
        ),
    ]
