# Generated by Django 3.2.4 on 2021-06-22 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_rented_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='rented',
            field=models.BooleanField(default=True),
        ),
    ]
