# Generated by Django 3.2.4 on 2021-06-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210622_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
