# Generated by Django 3.2.4 on 2021-06-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_last_rented_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default='The Great Gatsby'),
            preserve_default=False,
        ),
    ]
