# Generated by Django 3.2.4 on 2021-06-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210622_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='F. Scott Fitzgerald'),
            preserve_default=False,
        ),
    ]
