# Generated by Django 3.2.4 on 2021-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rented_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
