# Generated by Django 3.2.4 on 2021-06-23 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_rented_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rented_user_id',
            new_name='renting_user_id',
        ),
    ]
