# Generated by Django 3.2.4 on 2021-06-23 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_rented_user_id_book_renting_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='last_rented_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rented',
        ),
        migrations.AddField(
            model_name='book',
            name='last_rented_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
