# Generated by Django 3.2.4 on 2021-06-23 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210622_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='due_date',
            new_name='rental_due_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='last_rented_start_date',
            new_name='rental_start_date',
        ),
    ]
