# Generated by Django 3.2.4 on 2021-06-23 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210622_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rental_start_date',
        ),
        migrations.AddField(
            model_name='book',
            name='days_rented',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
