# Generated by Django 3.2.4 on 2021-06-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210622_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='days_rented',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
