# Generated by Django 3.2.4 on 2021-06-24 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0013_alter_book_days_rented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='renting_user_id',
        ),
        migrations.AddField(
            model_name='book',
            name='renting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
