# Generated by Django 3.2.4 on 2021-06-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20210624_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='book_type',
            field=models.CharField(max_length=50),
        ),
    ]
