# Generated by Django 3.2.4 on 2021-06-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_booktype_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktype',
            name='min_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booktype',
            name='min_days_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
